set(_CATKIN_CURRENT_PACKAGE "erica_gui")
set(erica_gui_VERSION "0.1.0")
set(erica_gui_MAINTAINER "robotemperor <robotemperor@gmail.com>")
set(erica_gui_PACKAGE_FORMAT "1")
set(erica_gui_BUILD_DEPENDS "qt_build" "roscpp" "robotis_math" "erica_arm_module_msgs" "libqt4-dev")
set(erica_gui_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(erica_gui_BUILDTOOL_DEPENDS "catkin")
set(erica_gui_BUILDTOOL_EXPORT_DEPENDS )
set(erica_gui_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(erica_gui_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(erica_gui_TEST_DEPENDS )
set(erica_gui_DOC_DEPENDS )
set(erica_gui_URL_WEBSITE "")
set(erica_gui_URL_BUGTRACKER "")
set(erica_gui_URL_REPOSITORY "")
set(erica_gui_DEPRECATED "")